VidlyReborn/Controllers/RentalsController.cs
using System.Web.Mvc;

namespace VidlyReborn.Controllers
{
    public class RentalsController : Controller
    {
        // GET
        public ActionResult New()
        {
            return View();
        }
    }
}

VidlyReborn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/css/datatables")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
@Html.Partial("_NavBar");
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/datatables")
@Scripts.Render("~/bundles/typeahead")
@RenderSection("scripts", required: false)
</body>
</html>

VidlyReborn/Views/Shared/_NavBar.cshtml
    <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("PAHAN", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                <li>@Html.ActionLink("New Rental", "New", "Rentals")</li>
            </ul>
            @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>